name: Run linter & tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [20.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: create .env
        run: cat .env.sample > .env

      - name: install packages
        run: yarn install

      - name: setup prisma
        run: yarn db:generate && yarn db:migrate

      - name: compile
        run: yarn build

      - name: lint
        run: yarn formatting

      - name: test
        run: yarn test

      - name: report coverage
        uses: MishaKav/jest-coverage-comment@main

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: trust known host key
        run: |
          mkdir -p ~/.ssh
          echo "bobs-server.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFKY8ALyTvnrEelcFVqbw9mLFcued5XtURan5EokkPsa" > ~/.ssh/known_hosts

      - name: rebuild & restart server
        run: |
          install -m 600 /dev/null deploy_key
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > deploy_key
          ssh -i deploy_key deploy@bobs-server.net
